#variables
IMGPATH = https://github.com/ucb-stat159/stat159-fall-2016/raw/master/projects/proj01/images/

#targets
.PHONY: clean skeleton

paper.html:

clean:
	rm paper.html

skeleton:
	cd images;\
	wget $(IMGPATH)git-logo.png $(IMGPATH)github-logo.png $(IMGPATH)markdown-logo.png;\
	wget $(IMGPATH)pandoc-logo.png $(IMGPATH)stat159-logo.png 